# Generated by Django 3.1.4 on 2020-12-27 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentFaculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentname', models.CharField(max_length=30)),
                ('facultyname', models.CharField(max_length=30)),
                ('rollno', models.CharField(max_length=20)),
                ('facultyid', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=30)),
                ('password', models.CharField(max_length=20)),
                ('collegename', models.CharField(max_length=50)),
                ('branch', models.CharField(max_length=10)),
                ('mobile', models.IntegerField()),
            ],
        ),
    ]
