# Generated by Django 3.1.4 on 2020-12-28 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newtask', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='college',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentname', models.CharField(max_length=30)),
                ('facultyname', models.CharField(max_length=30)),
                ('rollno', models.CharField(max_length=20)),
                ('facultyid', models.CharField(max_length=20)),
                ('semail', models.EmailField(max_length=30)),
                ('femail', models.EmailField(max_length=30)),
                ('spassword', models.CharField(max_length=20)),
                ('fpassword', models.CharField(max_length=20)),
                ('scollegename', models.CharField(max_length=50)),
                ('fcollegename', models.CharField(max_length=50)),
                ('sbranch', models.CharField(max_length=10)),
                ('fbranch', models.CharField(max_length=10)),
                ('smobile', models.IntegerField(null=True)),
                ('fmobile', models.IntegerField(null=True)),
                ('facultySal', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='StudentFaculty',
        ),
    ]
