# Generated by Django 3.1.4 on 2020-12-29 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newtask', '0002_auto_20201228_2106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='college',
            name='facultySal',
        ),
    ]
